### ISSUE TITLE
Schema import in hello_world tutorial does not work.

### ISSUE THREAD

**Issue by thenoahhein** [steprz/stepzen-schemas#48]
Trying to follow along with the hello_world tutorial on the main website. It asks me to import a stepzen schema by running `stepzen import weatherreport`. When I run this command I get: "Error: Cannot find the schema weatherreport".

**Comment by Cerchie** [comment]
Thank you for bringing this to our attention, @nheingit . We are sorry for this interruption to your tutorial and are getting to work on it. 

For now, can you use `stepzen import openweathermap` and `stepzen import ip-api` in place of `stepzen import weatherreport` and `stepzen import  location-weatherreport`, respectively ?

**Comment by thenoahhein** [comment]
Yes! Both of those work. I had found the `openweathermap` looking through the repo but hadn't stumbled across the `ip-api`. Thanks for the help.

**Comment by Cerchie** [comment]
My pleasure. We have fixed the commands so they are working as presented in the docs now. Thanks again for bringing this up!
