### ISSUE TITLE
Issue Importing 'twilio'

### ISSUE THREAD

**Issue by rdegges** [steprz/stepzen-schemas#64]
Hey all!

I'm trying to play around with the Twilio schema, but am having some issues getting it running. On a fresh install of the stepzen CLI, if I run: `npx stepzen import twilio` I'm prompted for my account SID + auth token (yey!), but then get the following error:

```
npx stepzen import twilio
? What would you like your endpoint to be called? api/twilio
Created /Users/rdegges/Drive/Sync/Code/testing/stepzen.config.json
Downloading from StepZen...... done

? What is the Account SID for your twilio API? [hidden]
? What is your auth token for your twilio API? [hidden]

Generating schemas...... !
    Error: Cannot copy '../cardinal/bin/cdl.js' to a subdirectory of itself, 
    '../cardinal/bin/cdl.js'.
npm ERR! code 1
npm ERR! path /Users/rdegges/Drive/Sync/Code/testing
npm ERR! command failed
npm ERR! command sh -c stepzen "import" "twilio"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rdegges/.npm/_logs/2021-05-24T03_17_37_187Z-debug.log
```

Any ideas? =D

**Comment by carloseberhardt** [comment]
Hey @rdegges .. what happens if you skip the npx bit.. just 
```
stepzen import twilio
```

That work?

**Comment by carloseberhardt** [comment]
BTW, thanks for the report! Looks like this is an issue with our cli rather than this template specifically, so we're digging in on that. Will update here when we resolve.

**Comment by carloseberhardt** [comment]
Closing this issue since we're tracking on the cli side. If anyone runs into something similar, please re-open and comment. This is not an issue with the schema-repository, but rather a problem with how the cli generating the schema based on the template.
